language: node_js
os:
  - osx
node_js:
  - 14
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  cleanup: true
  token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public